headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[dev]
command = "npm run dev"
port = 5173.0

[functions]

[functions."*"]

[build]
publish = "D:\\我的资料\\APP资料\\智盈AI\\dist"
publishOrigin = "config"
commandOrigin = "ui"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]